// Code generated by ppgen (github.com/aybabtme/ppgen).
//
// command:
// 		ppgen nop -type UserDB -src db.go
//
// DO NOT EDIT!

package example

import (
	"context"
	"testing"
)

func TestNopUserDB(t *testing.T) {
	tests := []struct {
		name  string
		check func(UserDB)
	}{
		{name: "Create", check: func(userdb UserDB) { userdb.Create("") }},
		{name: "Get", check: func(userdb UserDB) { userdb.Get("") }},
		{name: "Delete", check: func(userdb UserDB) { userdb.Delete(nil) }},
		{name: "List", check: func(userdb UserDB) { userdb.List(func() (out context.Context) { return out }()) }},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.check(NopUserDB())
		})
	}
}
