// Code generated by ppgen (github.com/aybabtme/ppgen).
// DO NOT EDIT!

package example

import "testing"

func TestNopUserDB(t *testing.T) {
	tests := []struct {
		name  string
		check func(UserDB)
	}{
		{name: "Create", check: func(userdb UserDB) { userdb.Create("") }},
		{name: "Get", check: func(userdb UserDB) { userdb.Get("") }},
		{name: "Delete", check: func(userdb UserDB) { userdb.Delete(nil) }},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.check(NopUserDB())
		})
	}
}
